version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - BACKEND_API_KEY=${BACKEND_API_KEY}
      - REDIS_URL=redis://redis:6379
      - WEBHOOK_MODE=true
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bot
    restart: unless-stopped

volumes:
  redis_data:
